---
- hosts: nfsserver
  become: true
  ignore_unreachable: yes
  ignore_errors: yes
  tasks:
    - name: utility present debian-like
      ansible.builtin.apt:
        name:
          - nfs-kernel-server
        state: present
        update_cache: yes
    - name: nfs server folder
      shell: |
        mkdir -p /nfs_volumes
        chmod -R 777 /nfs_volumes/
        echo "/nfs_volumes *(rw,sync,no_subtree_check,no_root_squash,insecure)">>/etc/exports
        sudo exportfs -rv
        showmount -e
        systemctl restart nfs-kernel-server rpcbind

    - name: apply on master
      shell: kubectl apply -f ./ansible/kubernetes/nfs-StorageClass/1nfs.yaml -f ./ansible/kubernetes/nfs-StorageClass/2nfs.yaml -f ./ansible/kubernetes/nfs-StorageClass/3nfs.yaml -f ./ansible/kubernetes/nfs-StorageClass/4nfs.yaml
      delegate_to: master1